account/urls.py
from django.urls import path
from .import views as v

urlpatterns = [
    
    
    path("/add",v.add, name='add'),
    path("/loginuser",v.loginuser,name='log'),
    path("/Logout",v.logot,name='logot'),
    path("/Search",v.srch,name="srch")
    #name is short name form of path/maybe view
    
      
    

  
]

bms/urls.py
from django.contrib import admin
from django.urls import path,include
from account .views import home

urlpatterns = [
    path('',home),
    path('admin/', admin.site.urls),
 
    path("account",include(("account.urls","account"),namespace="acc")),
    path("deposit",include(("deposit.urls","deposit"),namespace="dep")),
    path("withdraw",include(("withdraw.urls","withdraw"),namespace="wit")),
    # path('pathname',include("app.urls","appname")appnminshrtct="exp"
]

deposit/urls.py
from django.urls import path
from .import views as v

urlpatterns = [
      path("/Add",v.adddep,name="add"),
      path("/List",v.list,name="list"),
       
    
    # path("/abc",v.'abc')

  
]

withdraw/urls.py
from django.urls import path
from .import views as v

urlpatterns = [
     path("/Add",v.addwithdraw,name="add"),
     path("/List",v.list,name="list")
    
    # path("/abc",v.'abc')

  
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




# Create your models here.

deposit/models.py
from django.db import models
from django.contrib.auth.models import User


class DepositModel(models.Model):
    deposit_amount=models.IntegerField()
    deposit_type=models.CharField(max_length=30)
    deposit_description=models.TextField(max_length=30)
    deposit_day=models.CharField(max_length=30)
    deposit_date=models.DateField()
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,related_name="deposit")
    
    
    
    # user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,related_name="expense")
    
    class Meta:
        db_table="deposit"
        
    def __str__(s):
        return s.user.username        
    

# Create your models here.

withdraw/models.py
from django.db import models
from django.contrib.auth.models import User

class WithdrawModel(models.Model):
    
    
    withdraw_amount=models.IntegerField()
    withdraw_date=models.DateField()
    withdraw_description=models.TextField(max_length=30)
    withdraw_day=models.TextField(max_length=30)
    withdraw_type=models.TextField(max_length=30)
   
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,related_name="withdraw")
    
    
    
    class Meta:
        db_table="withdraw"
        
    def __str__(s):
        return s.user.username     
    


# Create your models here.

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from deposit.models import DepositModel
from withdraw.models import WithdrawModel

def home(request):
    return render(request,"home.html")


def add(request):
    if request.method == "POST":
        uname = request.POST.get("username")
        uemail = request.POST.get("email")
        upassword = request.POST.get("password")
        ufirst_name = request.POST.get("first_name")
        ulast_name = request.POST.get("last_name")
        uis_staff = request.POST.get("is_staff")
        
        
        # Corrected line: Use the actual password provided by the user
        obj = User.objects.create_user(username=uname, email=uemail, password=upassword,first_name=ufirst_name,last_name=ulast_name,is_staff=uis_staff)
        obj.save()
        return redirect("/account/add")
    else:
        return render(request, "form.html")
    


def loginuser(request):
    if request.method == "POST":
        uname = request.POST.get("uname")
        pswd = request.POST.get("upassword")
        user = authenticate(request, username=uname, password=pswd)
        # upassword=pswd=password
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            d = {"msg": "Invalid username and password"}
            return render(request, "login.html", d)
        

    else:
        return render(request, "login.html")
        
def logot(request):
    logout(request)
    return redirect("/")
#data is deleted when u use logoutrediert function from workbench  

def srch(request):
    uid=request.session.get("_auth_user_id")
    #it takes primery key
    obj=User.objects.get(id=uid)
    srchdata=request.GET.get('srch')
    datad=DepositModel.objects.filter(deposit_description__contains=srchdata,user=obj)
    #filter is giving a particular data
    dataw=WithdrawModel.objects.filter(withdraw_description__contains=srchdata,user=obj)
    #contain work like="%s%"
    
    d={
        "data1": datad,
        "data2": dataw,
        

    }
    return render(request,"srch.html",d)
    

# session key is a pswd
# Create your views here.
  
    
    
    
    
        


    
   

deposit/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .models import DepositModel





def adddep(request):
  if request.method=="POST":  
    amt=request.POST.get("amt")
    type=request.POST.get("type")
    date=request.POST.get("date")
    day=request.POST.get("day")
    description=request.POST.get("description")
    uid=request.session.get("_auth_user_id")
    #it tsakes user id from auth_user
    #it takes id of 
    obj=User.objects.get(id=uid)


    objd=DepositModel()
    objd.deposit_amount=amt
    objd.deposit_type=type
    objd.deposit_date=date
    objd.deposit_day=day
    objd.deposit_description=description
    objd.user=obj
    objd.save()
    return redirect("/")
  #for backtend

  else:
    print(request.session.items())
    return render(request,"deposit.html")
  
  
  
def list(request):
  uid=request.session.get("_auth_user_id")
  obj=User.objects.get(id=uid)
  data=DepositModel.objects.filter(user=obj)
  #use for some particular data u want filter
  d={
      "data":data
  }
  return render(request,"depdetails.html",d)
#for frontend







# Create your views here.

withdraw/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .models import WithdrawModel

def addwithdraw(request):
  if request.method=="POST":  
    amt=request.POST.get("amt")
    type=request.POST.get("type")
    date=request.POST.get("date")
    day=request.POST.get("day")
    description=request.POST.get("description")
    uid=request.session.get("_auth_user_id")
    #it takes auth-user id
    obj=User.objects.get(id=uid)


    objw=WithdrawModel()
    # use model from model
    objw.withdraw_amount=amt
    objw.withdraw_type=type
    objw.withdraw_date=date
    objw.withdraw_day=day
    objw.withdraw_description=description
    objw.user=obj
    objw.save()
    return redirect("/")

  else:
    return render(request,"withdraw.html")

  
def list(request):
  uid=request.session.get("_auth_user_id")
  obj=User.objects.get(id=uid)
  data=WithdrawModel.objects.filter(user=obj)
  #use for some particular data want
  #u use filter u see only login person explist and  inclist
  d={
    "data":data
  }
  return render(request,"withdrawdetails.html",d)
  


# Create your views here.

account/templates/depdetails.html
{%extends "master.html" %}

{%block 'main'%}



<table  class="table">
   
    
    <thead>
        <tr  class="table-info"  >
            <th>SrNo</th>
            <th scope="col">Deposit_Amount</th>
            <th scope="col">Deposit_Type</th>
            <th scope="col">Deposit_Day</th>
            <th scope="col">Deposit_Date</th>
            <th scope="col">Deposit_Description</th>
        </tr>
    </thead>
    <tbody>
        {%for d in data%}
        <tr class="table-danger" >
            <th>{{d.id}}</th>
            <td >{{d.deposit_amount}}</td>
            <td>{{d.deposit_type}}</td>
            <td>{{d.deposit_day}}</td>
            <td>{{d.deposit_date}}</td>
            <td>{{d.deposit_description}}</td>
        </tr>
        {%endfor%}
    </tbody>

</table>
{%endblock%}

account/templates/deposit.html
{%extends 'master.html'%}



{%block 'main'%}
<center><h1 class="mt-2 mb-3">Add Deposit Details!!</h1></center>
<form method="post" >
    {%csrf_token%}

    {% comment %} <div class="row mb-3">
      <label for="inputEmail3" class="col-sm-2 col-form-label" style="font-size:30px">Add Amount</label>
      <div class="col-sm-10">
        <input type="number" class="form-control" id="inputEmail3" name="amt">
      </div>
    </div>
     {% endcomment %}
    <div class="row mb-3">
      <label for="inputEmail3" class="col-sm-2 col-form-label" style="font-size:30px">Deposit Amount</label>
      <div class="col-sm-10">
        <input type="number" class="form-control" id="inputEmail3" name="amt">
      </div>
    </div>
    
    <div class="row mb-3">
      <label for="inputPassword3" class="col-sm-2 col-form-label" style="font-size:30px">Deposit Type</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputPassword3" name="type">
      </div>
    </div>

    <div class="row mb-3">
        <label for="inputPassword3" class="col-sm-2 col-form-label" style="font-size:30px">Day</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="inputPassword3" name="day">
        </div>
      </div>
    
    <div class="form-floating row mb-3">
        <textarea class="form-control" placeholder="add description" id="floatingTextarea" name="description"></textarea>
        <label for="floatingTextarea" style="font-size:20px">Add description</label>
    </div>

    <div id="date-picker-example" class="md-form md-outline input-with-post-icon datepicker row mb-3">
        <label for="example" style="font-size:30px">Date</label>
        <input placeholder="Select date" type="date" id="example" class="form-control" name="date">
        
        <i class="fas fa-calendar input-prefix"></i>
    </div>
   
    <button type="submit" class="btn btn-primary" style="font-size:30px">Add</button>
  </form>
{%endblock%}

account/templates/form.html
{% extends 'master.html' %}

{% block 'main' %}
  <h1>Welcome to the singup/form page</h1>
  {% comment %} <h1 class="text-primary">Welcome to the singup/form page</h1> {% endcomment %}

  <form class="mt-5 bg- p-5" method="post">
    {% csrf_token %}
    
    <div class="mb-3">
      <label for="first_name" class="form-label">firstname</label>
      <input type="text" class="form-control" id="first_name" name="first_name">
    </div>

    <div class="mb-3">
      <label for="last_name" class="form-label">lastname</label>
      <input type="text" class="form-control" id="last_name" name="last_name">
    </div>

    <div class="mb-3">
      <label for="username" class="form-label">Username </label>
      <input type="text" class="form-control" id="username" name="username">
    </div>


    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
      <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name="email">
    </div>

    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>


      <div class="mb-3">
        <label for="is_staff" class="form-label">staff</label>
        <input type="text" class="form-control" id="is_staff" name="is_staff">
      </div> 

    <button type="submit" class="btn btn-primary">Submit</button>

  </form>
{% endblock %}

account/templates/home.html
{%extends 'master.html'%} 

{%block 'main'%} 

<h1> WELCOME TO  THE  BANK MANAGEMENT SYSTEM </h1>

{%endblock%} 

account/templates/login.html
{% extends 'master.html' %}

{% block 'main' %}
<h1>Welcome to the login page</h1>


  {% if msg %}
    <h1>{{ msg }}</h1>
  {% endif %}

  <form class="mt-5 bg-primery" method="post">
    {% csrf_token %}
    

    <div class="mb-3">
      <label for="username" class="form-label">Username</label>
      <input type="text" class="form-control" id="username" name="uname">
    </div>

 

    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" class="form-control" id="password" name="upassword">
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

account/templates/master.html
<!DOCTYPE html>
<html lang="en">
 
<head>
{% load static %}
   
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %} <link rel="stylesheet" href="{% static'css/boost.css'%}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/boost.css' %}">
    <style>
      body{
        background-color:rgb(0, 128, 128);
        color:white;
      }
      header{
        background-color:rgb(171, 245, 244);
        color:white;
        font-size:20px;
        font-color:white;
      }
    </style>
      
    
</head>
<body>
  {% comment %} <nav class="cl1">
    <nav class="cl2" {% endcomment %}
  <header>
    
    <nav class="navbar bg-dark navbar-expand-lg border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          {%if user.is_authenticated%}
          <a class="navbar-brand" href="/">{{user}}</a>
          {%else%}
          <a class ="navbar-brand" href="/">!User</a>
          {%endif%}

          <a class="navbar-brand" href="/" style="font-size:20px">Home</a>
          {% comment %} #home is show every time u use any condition  also appplied a enternal css{% endcomment %}

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

               {% if user.is_authenticated %} 
              {% comment %} <li  class="nav-item">
                <a class="nav-link active" href="/">HOME</a>
  
              </li> {% endcomment %}
               
              
              {% comment %} #condition is here {% endcomment %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"  role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 Deposit
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item"  href="{%url 'dep:add'%}">Add Deposit details</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{%url 'dep:list'%}">Deposit List</a></li>
                </ul>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 Withdraw
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{%url 'wit:add'%}">Add Withdraw detail</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{%url 'wit:list'%}">Withdraw List</a></li>
                </ul>
              </li>

              
              <form class="d-flex" role="search"  action="{%url 'acc:srch'%}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="srch">
                <button class="btn btn-outline-success" type="submit"> <center>SEARCH</center></button>
              </form>
              

              <li>
              <a class="nav-link active" aria-current="page" href="{%url 'acc:logot'%}">Logout</a>
              <!-- #create chng here -->
              </li>
            

              {% comment %} <li class="nav-item">
              <a class="nav-link" href="{% url 'inc:add' %}">add income</a> 
              </li> {% endcomment %}
      

              {% else %}
              <li>
                  <a class="nav-link " href="{% url 'acc:add' %}" >Sing Up
              </li>
              
              
              <li> 
                  <a class="nav-link" href="{% url 'acc:log' %}">login</a>
              </li>
             {% endif %}
            </ul>
          </div>
        </div>
      </nav>
  </header>

  <div class="page">
    {% block 'main' %}

    {% endblock %}
  </div>

  <footer></footer>

  <script src="{% static 'js/boost.js' %}"></script>
</body>
</html>

account/templates/master1.html
<!DOCTYPE html>
<html lang="en">
 
<head>
{% load static %}
   
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %} <link rel="stylesheet" href="{% static'css/boost.css'%}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/boost.css' %}">
     
</head>
<body>
  {% comment %} <nav class="cl1">
    <nav class="cl2" {% endcomment %}
  <header>
    
    <nav class="navbar bg-dark navbar-expand-lg border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          {%if user.is_authenticated%}
          <a class="navbar-brand" href="/">{{user}}</a>
          {%else%}
          <a class ="navbar-brand" href="/">!User</a>
          {%endif%}

          <a class="navbar-brand" href="/" style="font-size:20px" &#128516;>Home</a>
          {% comment %} #home is show every time u use any condition  also appplied a enternal css{% endcomment %}

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              {% if user.is_authenticated %} 
           
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"  href="/" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Deposit
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item"  href="{%url 'dep:add'%}">Deposit amount</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{%url 'dep:list'%}">Deposit List</a></li>
                </ul>
            </li>
          </div>   

            {% comment %} <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               INCOME
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item"  href="{%url 'dep:add'%}">ADD INCOME</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{%url 'dep:list'%}">INCOME LIST</a></li>
              </ul>
            </li>
          </div>      {% endcomment %}
            
          {% comment %} <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                withdraw
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item"  href="{%url 'wit:add'%}">Deposit amount</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{%url 'wit:list'%}">Deposit List</a></li>
              </ul>
          </li>  {% endcomment %}
                

             

              
          {% comment %} <form class="d-flex" role="search"  action="{%url 'acc:srch'%}">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="srch">
              <button class="btn btn-outline-success" type="submit"> <center>Search</center></button>
          </form>   {% endcomment %}
              

              <li>
              <a class="nav-link active" aria-current="page" href="{%url 'acc:logot'%}">Logout</a>
              <!-- #create chng here -->
              </li>
              {% else %}
              <li>
                  <a class="nav-link " href="{% url 'acc:add' %}" >Sing Up
              </li>
              
              
              <li> 
                  <a class="nav-link" href="{% url 'acc:log' %}">Login</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
  </header>

  <div class="page">
    {% block 'main' %}

    {% endblock %}
  </div>

  <footer></footer>

  <script src="{% static 'js/boost.js' %}"></script>
</body>
</html>

account/templates/master2.html
<!DOCTYPE html>
<html lang="en">
 
<head>
{% load static %}
   
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/boost.css' %}">
  
</head>
<body>
  <nav class="cl1">
  <nav class="cl2">
  <header>
    
    <nav class="navbar bg-dark navbar-expand-lg border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          {%if user.is_authenticated%}
          <a class="navbar-brand" href="/">{{user}}</a>
          {%else%}
          <a class ="navbar-brand" href="/">!User</a>
          {%endif%}

          <a class="navbar-brand" href="/" style="font-size:20px" &#128516;>HOME</a>
          {% comment %} #home is show every time u use any condition  also appplied a enternal css{% endcomment %}

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

               {% if user.is_authenticated %} 
              {% comment %} <li  class="nav-item">
             
  
              </li>  {% endcomment %}
               
              
              {% comment %} #condition is here {% endcomment %}
            <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                   INCOME
                 </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item"  href="{%url 'dep:add'%}">ADD INCOME</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{%url 'dep:list'%}">INCOME LIST</a></li>
                    </ul>
            </li>

             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 EXPENSE
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{%url 'dep:add'%}">ADD EXPENSE</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{%url 'dep:list'%}">EXPENSE LIST</a></li>
                </ul>
              </li>

              
              {% comment %} <form class="d-flex" role="search"  action="{%url 'acc:srch'%}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="srch">
                <button class="btn btn-outline-success" type="submit"> <center>SEARCH</center></button>
              </form> {% endcomment %}
              

              <li>
              <a class="nav-link active" aria-current="page" href="{%url 'acc:logot'%}">LOGOUT</a>
              <!-- #create chng here -->
              </li>
            

              {% comment %} <li class="nav-item">
              <a class="nav-link" href="{% url 'inc:add' %}">add income</a> 
              </li> {% endcomment %}
      

              {% else %}
              <li>
                  <a class="nav-link " href="{% url 'acc:add' %}" >SING UP
              </li>
              
              
              <li> 
                  <a class="nav-link" href="{% url 'acc:log' %}">LOGIN</a>
              </li>
             {% endif %}
            </ul>
          </div>
        </div>
    </nav>
  </header>

  <div class="page">
    {% block 'main' %}

    {% endblock %}
  </div>

  <footer></footer>

  <script src="{% static 'js/boost.js' %}"></script>
</body>
</html>

account/templates/srch.html
{%extends 'master.html' %}
{%block 'main'%}
<h1>search</h1>
<table  border="4px" class="table">
    <thead>
        <tr  class="table-info">
            <th >SrNo</th>
            <th scope="col" >Amount</th>
            <th  scope="col">Type</th>
            <th scope="col">Day</th>
            <th scope="col">Date</th>
            <th scope="col">Description</th>
            <th scope="col">data</th>
            
        </tr>
       
    </thead>
    <tbody>
        {%for d in data1%}
     
        <tr>
            <th  class="table-danger" scope="row">{{d.id}}</th>
            <td class="table-danger">{{d.deposit_amount}}</td>
            <td class="table-danger">{{d.deposit_type}}</td>
            <td class="table-danger">{{d.deposit_day}}</td>
            <td class="table-danger">{{d.deposit_date}}</td>
            <td class="table-danger">{{d.deposit_description}}</td>
            <td  class="table-danger">deposit</td>
            
        </tr>
        {%endfor%}
        {%for w in data2%}
     
        <tr >
            <th  class="table-primary" scope="row">{{w.id}}</th>
            <td  class="table-primary" >{{w.withdraw_amount}}</td>
            <td  class="table-primary" >{{w.withdraw_type}}</td>
            <td   class="table-primary">{{w.withdraw_day}}</td>
            <td   class="table-primary">{{w.withdraw_date}} </td>
            <td   class="table-primary">{{w.withdraw_description}} </td>
            <td   class="table-primary">withdraw</td>
         
        </tr>
        {%endfor%}
      
        
    </tbody>
</table>

{%endblock%}

account/templates/withdraw.html
{%extends 'master.html'%}



{%block 'main'%}
<center><h1 class="mt-2 mb-3">Add withdraw Details!!</h1></center>
<form method="post" >
    {%csrf_token%}

    <div class="row mb-3">
      <label for="inputnmbr" class="col-sm-2 col-form-label" style="font-size:30px">Withdraw  amount</label>
      <div class="col-sm-10">
        <input type="number" class="form-control" id="inputnmbr" name="amt">
      </div>
    </div>
    
   
    <div class="row mb-3">
      <label for="inputPassword3" class="col-sm-2 col-form-label" style="font-size:30px">Withdraw Type</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputPassword3" name="type">
      </div>
    </div>

    <div class="row mb-3">
        <label for="inputPassword3" class="col-sm-2 col-form-label" style="font-size:30px">Day</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="inputPassword3" name="day">
        </div>
      </div>
    
    <div class="form-floating row mb-3">
        <textarea class="form-control" placeholder="add description" id="floatingTextarea" name="description"></textarea>
        <label for="floatingTextarea" style="font-size:20px">Add description</label>
    </div>

    <div id="date-picker-example" class="md-form md-outline input-with-post-icon datepicker row mb-3">
        <label for="example" style="font-size:30px">Date</label>
        <input placeholder="Select date" type="date" id="example" class="form-control" name="date">
        
        <i class="fas fa-calendar input-prefix"></i>
    </div>
   
    <button type="submit" class="btn btn-primary" style="font-size:30px">Add</button>
  </form>
{%endblock%}

account/templates/withdrawdetails.html
{%extends "master.html" %}

{%block 'main'%}

<table class="table">
    <thead>
        <tr class="table-info">
            <th  >SrNo</th>
            <th scope="col">withdraw Amount</th>
            <th scope="col">withdraw Type</th>
            <th  scope="col">withdraw Day</th>
            <th  scope="col">withdraw description</th> 
            <th  scope="col">withdraw Date</th> 
        </tr>
    </thead>
    <tbody>
        {%for w in data%}
        <tr  class="table-warning">
            <th>{{w.id}}</th>
            <td >{{w.withdraw_amount}}</td>
            <td >{{w.withdraw_type}}</td>
            <td >{{w.withdraw_day}}</td>
            <td >{{w.withdraw_description}} </td>
            <td >{{w.withdraw_date}} </td>
         
        </tr>
        {%endfor%}
    </tbody>

</table>
{%endblock%}